### ISSUE TITLE
Package METS OTHERCONTENTINFORMATIONTYPE requirement incompatible with the specification 

### ISSUE THREAD

**Issue by hmiguim** [DILCISBoard/SIARD-CITS#8]
At Package METS  the requirement SIARD_7 "For any mets/fileSec/fileGrp[@csip:CONTENTINFORMATIONTYPE that has the value “citssiard_v1_0”, there MUST be a @csip:OTHERCONTENTINFORMATIONTYPE attribute with a value taken from the vocabulary {SIARD_1.0; SIARD_2.0, SIARD_2.1, SIARD_2.2, Database_dump}. " in my point of view is not correct. 

According to the specification "There can easily be different representations of the same database located within one CSIP." Which in terms means that OTHERCONTENTINFORMATIONTYPE must not be restrictive at the package level but at the representation level.

**Comment by PhillipAasvangTommerholt** [comment]
I definitely agree that OTHERCONTENTINFORMATIONTYPE must not be restrictive at the package level but only at the representation level.

In the CITS SIARD specification I/we have tried to map the requirements to the corresponding CSIP requirements.
So if you look at SIARD_3 and SIARD_4 this is actually the case you are pleading for and it is in the METS ROOT element (CSIP3 and CSIP4) where this high level description is to be found and where you are actually not allowed to restrict your package to a specific SIARD specification.

SIARD_7 corresponds to CSIP63 in the fileSec which is where you have your pointers to the actual representations and at the same time describe which SIARD specification the representations are said to be compliant with. They are mandatory here since it is the intention that the package METS should "know" which kinds of representations it has. 

I hope this sheds enough light on the matter and that there is no flaw in the logic of the requirements? If not please let me know.
